name: places
description: My new Flutter project in Surf Flutter course

publish_to: 'none'

version: 1.4.10+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
